name: Go Multianalyzer Check
description: Run a set of golang.org/x/tools/go/analysis.Analyzers on a repository.
author: Christopher Tarry <chrisjt@sia.tech>
inputs:
  analyzers:
    description: List of analyzers.
    default:
      - go.sia.tech/jape.Analyzer
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: check
  color: green